package com.xworkz.app.boot;

import java.util.ArrayList;
import java.util.Collection;

import com.xworkz.app.dto.MlaDTO;

public class MlaRunner {

	public static void main(String[] args) {
		
		Collection<MlaDTO> mlaDTOs = new ArrayList<>();
		
		mlaDTOs.add(new MlaDTO("Mane Shrinivas", 42, "Hanagal", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Sanjeeva Matandoor", 30, "Puttur", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Aihole Duryodhan Mahalingappa", 0, "Raibag", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("D S Suresh", 40, "Tarikere", "Bharatiya Janata Party (BJP)", false, null));
		mlaDTOs.add(new MlaDTO("Yadwad Mahadevappa Shivalingappa", 50, "Ramadurg", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Siddu Savadi", 50, "Terdal", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("B C Nagesh", 60, "Tiptur", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("S Suresh Kumar", 30, "Rajajinagar", "Bharatiya Janata Party (BJP)", true, "male"));
		mlaDTOs.add(new MlaDTO("G B Jyothi Ganesh", 42, "Tumkur City", "Bharatiya Janata Party (BJP)", false, "female"));
		mlaDTOs.add(new MlaDTO("Jayaram A S", 36, "Turuvekere", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("K Raghupathi Bhat", 44, "Udupi", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Dr S Shivaraj Patil", 35, "Raichur", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("R Shankar", 44, "Ranebennur", "Karnataka Prajnyavantha Janatha Party (KPJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Basanagouda Somanagouda Patil (SASANUR)", 36, "Devara Hippargi", "Bharatiya Janata Party (BJP)",true , "male"));
		mlaDTOs.add(new MlaDTO("S Kumar Bangarappa", 38, "Soraba", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Nagendra L", 45, "Chamaraja", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("K Madal Virupakshappa", 57, "Channagiri", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Uday B Garudachar", 36, "Chickpet", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("C T Ravi", 47, "Chikmagalur", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("J C Madhuswamy", 68, "Chikkanayakanahalli", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("G H Thippa Reddy", 45, "Chitradurga", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("B M Sukumar Shetty", 22, "Baindur", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("K Shivanagouda Naik", 45, "Devadurga", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Ballary Virupakshappa Rudrappa", 24, "Byadagi", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Amrut Ayyappa Desai", 66, "Dharwad", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Paranna Ishwarappa Munavalli", 26, "Gangavathi", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("H Halappa", 33, "Sagara", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Shankar Patil Munenakoppa", 28, "Navalgund", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Dr Umesh G Jadhav", 45, "Chincholi", "Indian National Congress (INC)", true, "male"));
		mlaDTOs.add(new MlaDTO("Priyanka M Kharge", 30, "Chittapur", "Indian National Congress (INC)", false, "female"));
		mlaDTOs.add(new MlaDTO("Patil Mallanagouda Basavanagouda", 31, "Babaleshwar", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Ramalinga Reddy", 33, "B. T. M Layout", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("T Venkataramanaiah", 38, "Doddaballapur", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("C C Patil", 34, "Naragund", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("R Ashoka", 41, "Padmanaba Nagar", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Jolle Shashikala Annasaheb", 36, "Nippani", "Bharatiya Janata Party (BJP)", true, "male"));
		mlaDTOs.add(new MlaDTO("Venkatreddy Mundal", 37, "Yadagir", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("S R Vishwanath", 38, "Yelahanka", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("B Harshavardhan", 39, "Nanjangud", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("S Angara", 40, "Sullia", "Bharatiya Janata Party (BJP)", true, "female"));
		mlaDTOs.add(new MlaDTO("Achar Halappa Basappa", 41, "Yelburga", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Araga Jnanendra", 45, "Thirthahalli", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("K G Bopaiah", 43, "Virajpet", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Kalakappa Gurushanthappa Bandi", 44, "Ron", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("K B Ashok Naik", 45, "Shimoga Rural", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Narasimha Nayak (RAJU Gouda)", 46, "Shorapur", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("K S Eswarappa", 47, "Shimoga", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("B S Yediyurappa", 48, "Shikaripura", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Basavaraj Bommai", 49, "Shiggaon", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Rajkumar Patil", 50, "Sedam", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Visweswara Heggade Kageri", 51, "Sirsi", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Vishwanath Chandrashekar Mamani", 52, "Saundatti Yellamma", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("M S Somalingappa", 53, "Siruguppa", "Bharatiya Janata Party (BJP)", true, "male")); 
		mlaDTOs.add(new MlaDTO("Dattatraya Chandrasekar Patil Revoor (APPUGOUDA)", 54, "Gulbarga Dakshin", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Ramanna S Lamani", 54, "Shirahatti", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("M Chandrappa", 56, "Holalkere", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("V Somanna", 48, "Govindraj Nagar", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Lalaji R Mendon", 58, "Kaup", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("D Vedavyasa Kamath", 59, "Mangalore City South", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("N Linganna", 60, "Mayakonda", "Bharatiya Janata Party (BJP)", true, "male"));
		mlaDTOs.add(new MlaDTO("B Sriramulu", 53, "Molakalmuru", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Umanatha A Kotian", 54, "Moodabidri", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("A S Patil (NADAHALLI)", 38, "Muddebihal", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Karajola Govinda Maktappa", 64, "Mudhol", "Bharatiya Janata Party (BJP)", false, "female"));
		mlaDTOs.add(new MlaDTO("Aravinda Limbavali", 48, "Mahadevapura", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Katti Umesh Vishwanath", 36, "Hukkeri", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Preetham J Gowda", 67, "Hassan", "Bharatiya Janata Party (BJP)", true, "male"));
		mlaDTOs.add(new MlaDTO("C S Niranjan Kumar", 55, "Gundlupet", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("K Poornima", 42, "Hiriyur", "Bharatiya Janata Party (BJP)", false, "female"));
		mlaDTOs.add(new MlaDTO("Mane Shrinivas", 42, "mudhol", null, false, null));
		mlaDTOs.add(new MlaDTO("M P Appachu Ranjan", 70, "Madikeri", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("M P Renukacharya", 71, "Honnali", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Goolihatti D Shekar", 72, "Hosadurga", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Doddagoudar Mahantesh Basavantaray", 73, "Kittur", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Aravind Chandrakant Bellad", 74, "Hubli-Dharwad-West", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Roopali Santosh Naik", 75, "Karwar", "Bharatiya Janata Party (BJP)", false, "female"));
		mlaDTOs.add(new MlaDTO("Doddanagouda Gundanagouda Patil", 76, "Hungund", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("S V Ramachandra", 77, "Jagalur", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Prakash K S", 78, "Kadur", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("C M Nimbannavar", 79, "Kalghatagi", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Basavaraj Dadesugur", 80, "Kanakagiri", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("M P Kumaraswamy", 81, "Mudigere", "Bharatiya Janata Party (BJP)", true, "male"));
		mlaDTOs.add(new MlaDTO("Jagadish Shettar", 82, "Hubli-Dharwad-Central", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Olekar Neharu Chanabasappa", 83, "Haveri", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Gali Somashekara Reddy", 84, "Bellary City", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Dinesh Gundurao", 85, "Gandhinagar", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("V Sunil Kumar", 56, "Karkala", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("S A Ravindranatha", 37, "Davanagere North", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Abhay Patil", 68, "Belgaum Dakshin", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Guttedar Subhash Rukmayya", 49, "Aland", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Balachandra Lakshmanrao Jarakiholi", 40, "Arabhavi", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Prabhu B Chavhan", 51, "Aurad", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Veerabhadrayya (VEERANNA) Charantimath", 42, "Bagalkot", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("M Krishnappa", 63, "Bangalore South", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Rajesh Naik U", 44, "Bantwal", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("S Raghu", 35, "C.V Raman Nagar", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Dr C N Ashwath Narayana", 66, "Malleshwaram", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("G Karunakara Reddy", 57, "Harapanahalli", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Basawaraj Mattimud", 48, "Gulbarga Rural", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Harish Poonja", 36, "Belthangady", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Sunil Biliya Naik", 41, "Bhatkal", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Basanagouda Ramanagouda Patil(Yatnal)", 65, "Bijapur City", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Nirani Murugesh Rudrappa", 46, "Bilgi", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("M Satish Reddy", 65, "Bommanahalli", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("L A Ravisubramanya", 64, "Basavanagudi", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Dr Bharath Shetty Y", 35, "Mangalore City North", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("S A Ramadas", 46, "Krishnaraja", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("P Rajeev", 56, "Kudachi", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("N Y Gopalakrishna", 46, "Kudligi", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Dinakar Keshav Shetty", 65, "Kumta", "Bharatiya Janata Party (BJP)", true, "male"));
		mlaDTOs.add(new MlaDTO("Haladi Srinivasa Shetty", 38, "Coonadapur/Kundapura", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Anil S Benake", 54, "Belgaum Uttar", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("E Tukaram", 48, "Sandur", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("U T Khadar", 56, "Mangalore", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Raja Venkatappa Nayak", 46, "Manvi", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("M Srinivas", 36, "Mandya", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("C N Balakrishna", 58, "Sravanabelagola", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("D C Thammanna", 54, "Maddur", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("Dr K Annadani", 65, "Malavalli", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("A Manjunath", 54, "Magadi", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("Mane Shrinivas", 42, "", null, false, "male"));
		mlaDTOs.add(new MlaDTO("Ravindra Srikantaiah", 120, "Shrirangapattana", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("M V Veerabhadraiah", 121, "Madhugiri", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("S R Srinivas (VASU)", 35, "Gubbi", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("Anil Kumar C", 45, "Heggadadevankote", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Nagangouda Kandkur", 26, "Gurmitkal", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("Rajashekar Basavaraj Patil", 33, "Humnabad", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("C S Puttaraju", 36, "Melukote", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("R Narendra", 38, "Hanur", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("K J George", 30, "Sarvagnanagar", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("S Ramappa", 29, "Harihar", "Indian National Congress (INC)", true, "male"));
		mlaDTOs.add(new MlaDTO("Abbayya Prasad", 30, "Hubli-Dharwad-East", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Sharanabasappa Darshanapur", 31, "Shahapur", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("M T B Nagaraju", 32, "Hosakote", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("N A Haris", 33, "Shantinagar", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Suresh B S", 34, "Hebbal", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("L B P Bheema Naik", 35, "Hagaribommanahalli", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("K Raghavendra Basavaraj Hitnal", 36, "Koppal", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Tanveer Sait", 37, "Narasimharaja", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Shamanuru Shivashankarappa", 38, "Davanagere South", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("B C Patil", 39, "Hirekerur", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("G T Devegowda", 40, "Chamundeshwari", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("H Nagesh", 41, "Mulbagal", "Independent (IND)", false, "male"));
		mlaDTOs.add(new MlaDTO("Narayana Swamy L N", 42, "Devanahalli", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("-", 43, "Ramanagaram", "-", false, "male"));
		mlaDTOs.add(new MlaDTO("Lingesh K S", 44, "Belur", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("J K Krishnareddy", 45, "Chintamani", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("Bhusanur Ramesh Balappa", 46, "Sindgi", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("H D Revanna", 47, "Holenarasipura", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("Bandeppa Khasempur", 48, "Bidar South", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("D C Gowrishankar", 49, "Tumkur Rural", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("K Srinivasa Gowda", 50, "Kolar", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("K Mahadeva", 51, "Periyapatna", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("Narayana Gowda", 52, "Krishnarajapet", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("S R Mahesh", 53, "Krishnarajanagara", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("K Y Nanjegowda", 54, "Malur", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Ashvin Kumar M", 55, "T. Narasipura", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("Shamanuru Shivashankarappa", 38, "Davanagere South", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("B C Patil", 39, "Hirekerur", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("G T Devegowda", 40, "Chamundeshwari", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("H Nagesh", 41, "Mulbagal", "Independent (IND)", false, "male"));
		mlaDTOs.add(new MlaDTO("Narayana Swamy L N", 42, "Devanahalli", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("-", 43, "Ramanagaram", "-", false, "male"));
		mlaDTOs.add(new MlaDTO("Lingesh K S", 44, "Belur", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("J K Krishnareddy", 45, "Chintamani", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("Bhusanur Ramesh Balappa", 46, "Sindgi", "Bharatiya Janata Party (BJP)", false, "male"));
		mlaDTOs.add(new MlaDTO("H D Revanna", 47, "Holenarasipura", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("Bandeppa Khasempur", 48, "Bidar South", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("D C Gowrishankar", 49, "Tumkur Rural", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("K Srinivasa Gowda", 50, "Kolar", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("K Mahadeva", 51, "Periyapatna", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("Narayana Gowda", 52, "Krishnarajapet", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("S R Mahesh", 53, "Krishnarajanagara", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("K Y Nanjegowda", 54, "Malur", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Ashvin Kumar M", 55, "T. Narasipura", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("H D Kumaraswamy", 56, "Channapatna", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("Manjunatha R", 57, "Dasarahalli", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("H Viswanath", 58, "Hunsur", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("H K Kumaraswamy", 59, "Sakaleshpur", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("Nadagouda Venkatarao", 60, "Sindhanoor", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("Dr K Srinivasamurthy", 61, "Nelamangala", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("Suresh Gowda", 62, "Nagamangala", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("Devanand Fulasing Chavan", 63, "Nagthan", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("A T Ramaswamy", 64, "Arakalgud", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("K M Shivalinge Gowda", 65, "Arasikere", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("K Gopalaiah", 65, "Mahalakshmi Layout", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("B Satyanarayana", 56, "Sira", "Janata Dal (Secular) (JD(S))", false, "male"));
		mlaDTOs.add(new MlaDTO("S N K M Narayana Swamy", 32, "Bangarpet", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Pratapagouda Patil", 62, "Maski", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("K R Ramesh Kumar", 48, "Srinivasapur", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Deshpande Raghunath Vishwanathrao", 26, "Haliyal", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Siddaramaiah", 45, "Badami", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("B Narayan Rao", 65, "Basavakalyan", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Patil Shivananda Siddaramappa", 44, "Basavana Bagevadi", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Raheem Khan", 65, "Bidar", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Eshwara Bhimanna Khandre", 35, "Bhalki", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("B K Sangameshwara", 33, "Bhadravathi", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Yathindra S", 65, "Varuna", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Laxmi R Hebbalkar", 65, "Belgaum Rural", "Indian National Congress (INC)", false, "female"));
		mlaDTOs.add(new MlaDTO("T Raghumurthy", 32, "Challakere", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("B Nagendra", 56, "Bellary", "Indian National Congress (INC)", true, "male"));
		mlaDTOs.add(new MlaDTO("C Puttarangashetty", 54, "Chamarajanagar", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("H K Patil", 65, "Gadag", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("D K Shivakumar", 54, "Kanakapura", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("S T Somashekar", 55, "Yeshvanthapura", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("B Shivanna", 65, "Anekal", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Arbail Shivaram Hebbar", 34, "Yellapur", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Kaneez Fatima", 36, "Gulbarga Uttar", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("V Muniyappa", 64, "Sidlaghatta", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Ramesh Lakshmanrao Jarakiholi", 64, "Gokak", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("N H Shivashankara Reddy", 66, "Gowribidanur", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Mahesh Iranagouda Kumathalli", 65, "Athani", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Dr K Sudhakar", 49, "Chikkaballapur", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("N Mahesh", 49, "Kollegal", "Bahujan Samaj Party (BSP)", false, "male"));
		mlaDTOs.add(new MlaDTO("Anand Singh", 46, "Vijayanagara", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("J N Ganesh", 44, "Kampli", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Venkataramanappa", 44, "Pavagada", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("D S Hoolageri", 46, "Lingasagur", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Amaregouda Linganagouda Patil Bayyapur", 46, "Kushtagi", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Dr H D Ranganath", 44, "Kunigal", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Shivalli Channabasappa Satyappa", 41, "Kundagol", "Indian National Congress (INC)", false, "female"));
		mlaDTOs.add(new MlaDTO("R Akhanda Srinivasamurthy", 46, "Pulakeshinagar", "Indian National Congress (INC)", false, "female"));
		mlaDTOs.add(new MlaDTO("M Y Patil", 45, "Afzalpur", "Indian National Congress (INC)", true, "male"));
		mlaDTOs.add(new MlaDTO("Dr G Parameshwara", 54, "Koratagere", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Yashvantarayagouda Vittalagouda Patil", 54, "Indi", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Roopakala M", 46, "Kolar Gold Field", "Indian National Congress (INC)", false, "female"));
		mlaDTOs.add(new MlaDTO("Dr Anjali Hemant Nimbalkar", 44, "Khanapur", "Indian National Congress (INC)", false, "female"));
		mlaDTOs.add(new MlaDTO("Satish Lakshmanrao Jarakiholi", 45, "Yemkanmardi", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Munirathna", 66, "Rajarajeshwarinagar", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("T D Rajegowda", 56, "Sringeri", "Indian National Congress (INC)", true, "male"));
		mlaDTOs.add(new MlaDTO("Shrimanth Balasaheb Patil", 65, "Kagawad", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("B A Basavaraja", 66, "K.R. Pura", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Dr Ajay Dharam Singh", 56, "Jewargi", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Siddu B Nyamagouda", 65, "Jamakhandi", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Basanagouda Daddal", 35, "Raichur Rural", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("R Roshan Baig", 65, "Shivajinagar", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("C B Krishna Byregowda", 56, "Byatarayanapura", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Ganesh Prakash Hukkeri", 65, "Chikkodi-Sadalga", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("M Krishnappa", 65, "Vijayanagar", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("S N Subbareddy", 36, "Bagepalli", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Jameer Ahmed Khan", 39, "Chamarajpet", "Indian National Congress (INC)", true, "male"));
		mlaDTOs.add(new MlaDTO("Koujalgi Mahanthesh Shivananda", 71, "Bailhongal", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("P T Parameshwara Naik", 56, "Hadagali", "Indian National Congress (INC)", false, "male"));
		mlaDTOs.add(new MlaDTO("Soumya Reddy", 66, "Jayanagar", "Indian National Congress (INC)", false, "female"));
	
		System.out.println(" [total MLAs in karnataka :"+mlaDTOs.size()+"\n List of all MLA's >>\n ");
		mlaDTOs.forEach(element-> System.out.println("> "+element.getName()));
		System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ \n");
		System.out.println("MLA's whos age is gratter then 50 \n-------------------------------");
		mlaDTOs.stream().filter(element-> element.getAge()>50).forEach(element-> System.out.println("-> "+element.getName()));
		System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ \n");
		System.out.println("MLA's whos age is less then 50 \n-------------------------------");
		mlaDTOs.stream().filter(element-> element.getAge()<50).forEach(element-> System.out.println("-> "+element.getName()));
		System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ \n");
		System.out.println("male MLA's \n-------------------------------");
		mlaDTOs.stream().filter(element-> element.getGender().equals("male")).forEach(element-> System.out.println("-> "+element.getName()));
		System.out.println("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ \n");
		System.out.println("Female MLA's \n-------------------------------");
		mlaDTOs.stream().filter(element-> element.getGender().equals("female")).forEach(element-> System.out.println("-> "+element.getName()));


		
		
		
		
	}
	
	
}
